

# This file was *autogenerated* from the file criminal/main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_310717010502520989590157367261876774703 = Integer(310717010502520989590157367261876774703); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_179210853392303317793440285562762725654 = Integer(179210853392303317793440285562762725654); _sage_const_105268671499942631758568591033409611165 = Integer(105268671499942631758568591033409611165); _sage_const_1 = Integer(1)
from sage.all import *


def main():
    p = _sage_const_310717010502520989590157367261876774703 
    E = EllipticCurve(GF(p), [_sage_const_2 , _sage_const_3 ])
    G = E(
        _sage_const_179210853392303317793440285562762725654 , _sage_const_105268671499942631758568591033409611165 
    )
    n = randint(_sage_const_1 , p)
    Q = n * G
    print(n, Q)


if __name__ == "__main__":
    main()

