

# This file was *autogenerated* from the file ladder/main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_255 = Integer(255); _sage_const_19 = Integer(19); _sage_const_0 = Integer(0); _sage_const_486662 = Integer(486662); _sage_const_1 = Integer(1); _sage_const_9 = Integer(9); _sage_const_0x1337C0DECAFE = Integer(0x1337C0DECAFE)
from sage.all import *


def main():
    p = (_sage_const_2  ** _sage_const_255 ) - _sage_const_19 
    E = EllipticCurve(GF(p), [_sage_const_0 , _sage_const_486662 , _sage_const_0 , _sage_const_1 , _sage_const_0 ])
    P = E.lift_x(_sage_const_9 )
    n = _sage_const_0x1337C0DECAFE 
    print((n * P).xy())


if __name__ == "__main__":
    main()

