

# This file was *autogenerated* from the file ecc3/main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_9739 = Integer(9739); _sage_const_497 = Integer(497); _sage_const_1768 = Integer(1768); _sage_const_815 = Integer(815); _sage_const_3190 = Integer(3190); _sage_const_1829 = Integer(1829); _sage_const_0 = Integer(0)
from sage.all import *
import hashlib


def main():
    E = EllipticCurve(GF(_sage_const_9739 ), [_sage_const_497 , _sage_const_1768 ])
    Q_A = E(_sage_const_815 , _sage_const_3190 )
    n_B = _sage_const_1829 
    shared_secret = str((Q_A * n_B).xy()[_sage_const_0 ])
    print(hashlib.sha1(shared_secret.encode("utf-8")).hexdigest())


if __name__ == "__main__":
    main()

