

# This file was *autogenerated* from the file ecc0/main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_9739 = Integer(9739); _sage_const_497 = Integer(497); _sage_const_1768 = Integer(1768); _sage_const_8045 = Integer(8045); _sage_const_6936 = Integer(6936)
from sage.all import *


def main():
    # E: Y2 = X3 + 497 X + 1768, p: 9739
    E = EllipticCurve(GF(_sage_const_9739 ), [_sage_const_497 , _sage_const_1768 ])
    P = E(_sage_const_8045 , _sage_const_6936 )
    Q = -P
    print(Q)


if __name__ == "__main__":
    main()

