

# This file was *autogenerated* from the file ecc2/main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_9739 = Integer(9739); _sage_const_497 = Integer(497); _sage_const_1768 = Integer(1768); _sage_const_2339 = Integer(2339); _sage_const_2213 = Integer(2213); _sage_const_7863 = Integer(7863)
from sage.all import *


def main():
    E = EllipticCurve(GF(_sage_const_9739 ), [_sage_const_497 , _sage_const_1768 ])
    P = E(_sage_const_2339 , _sage_const_2213 )
    print(_sage_const_7863  * P)


if __name__ == "__main__":
    main()

